name: Abanu Testing
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Update Package respository
        run: sudo apt-get -y -o Acquire::Check-Valid-Until=false update
      - name: Install Packages
        run: sudo apt-get install -y --no-install-recommends git wget nasm qemu-system-x86 mtools xorriso grub-common grub-pc-bin grub-efi-amd64-bin grub-efi-ia32-bin
      - name: debug
        run: ls $GITHUB_WORKSPACE
      - name: Set Permissions
        run: chmod +x $GITHUB_WORKSPACE/abctl
      - name: Configure
        run: $GITHUB_WORKSPACE/abctl configure cloud-test
      - name: Build
        run: $GITHUB_WORKSPACE/abctl build all
      - name: Test
        run: $GITHUB_WORKSPACE/abctl test cloud
